print("Hello world")
print("line 2")
print("adding today")
print("today is tuesday")
print("line adding for new branch")
print("code for sample")
print("all the best")
print("added by another developer")
print("line 7")

